#!/bin/bash

php /home/zimzim/www/app/console $@

for param in $@
do
    if [ $param = "cache:clear" ] || [ $param = "cache:warmup" ]
    then
        chmod -R 0770 /home/zimzim/www/app/cache
        chown -R zimzim:www-data /home/zimzim//www/app/cache
        chmod -R 0770 /home/zimzim//www/app/logs
        chown -R zimzim:www-data /home/zimzim/www/app/logs
        break
    fi
done