#!/bin/bash

php /home/centoweb/www/app/console $@

for param in $@
do
    if [ $param = "cache:clear" ] || [ $param = "cache:warmup" ]
    then
        chmod -R 0770 /home/centoweb/www/app/cache
        chown -R www-data /home/centoweb//www/app/cache
        chmod -R 0770 /home/centoweb//www/app/logs
        chown -R www-data /home/centoweb/www/app/logs
        break
    fi
done